#!/bin/bash -login
 
#PBS -l walltime=3:59:00,nodes=1:ppn=1,mem=2gb
#PBS -j oe
#PBS -t 51991-52090

### change to the working directory where your code is located
cd ${SCRATCH}/genomesize_extinction/avida/config_files
mkdir -p ../data_fixedlength_N20_mu001
### call your executable
./avida -set DATA_DIR ../data_fixedlength_N20_mu001/replicate_${PBS_ARRAYID} -set RANDOM_SEED ${PBS_ARRAYID} -set WORLD_X 20 -set WORLD_Y 1 -set BIRTH_METHOD 4 -set VERBOSITY 0 -set COPY_MUT_PROB 0.0 -set DIV_MUT_PROB 0.01 -set DIVIDE_INS_PROB 0.0 -set DIVIDE_DEL_PROB 0.0 -set REQUIRE_EXACT_COPY 1