#!/bin/bash -login
#PBS -l walltime=3:59:00,nodes=1:ppn=1,mem=2gb
#PBS -j oe
cd ${HOME}/Documents/genomesize_extinction/avida/config_files
./avida -a -set ANALYZE_FILE analyze_varlength_slip_N20_mu001_largegenomes.cfg -set DATA_DIR .. -set WORLD_X 20 -set WORLD_Y 1 -set BIRTH_METHOD 4 -set COPY_MUT_PROB 0.0 -set DIV_MUT_PROB 0.01 -set DIVIDE_INS_PROB 0.0 -set DIVIDE_DEL_PROB 0.0 -set DIVIDE_SLIP_PROB 0.01 -set REQUIRE_EXACT_COPY 1